### ISSUE TITLE
Read timeouts

### ISSUE THREAD

**Issue by impredicative** [relrod/dagd#58]
I am seeing multiple read timeout errors this morning. Times are Eastern.

> 8:31:02 AM Failed to receive a response for long URL https://www.marketwatch.com/story/cleveland-cliffs-shares-rise-on-higher-annual-fixed-prices-for-steel-01671713469?siteid=yhoof2&yptr=yahoo  in attempt 3 of 3. The exception is: ConnectTimeout: HTTPSConnectionPool(host='[da.gd](http://da.gd/)', port=443): Max retries exceeded with url: /s (Caused by ConnectTimeoutError(<urllib3.connection.HTTPS

> 8:33:38 AM Failed to receive a response for long URL https://barrons.com/articles/self-driving-startup-tusimple-cut-staff-restructuring-51671715893?mod=RTA  in attempt 3 of 3. The exception is: ConnectTimeout: HTTPSConnectionPool(host='[da.gd](http://da.gd/)', port=443): Max retries exceeded with url: /s (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fca146a

> 8:42:52 AM Failed to receive a response for long URL https://dailycoin.com/former-ftx-alameda-research-executives-cooperating-with-the-authorities/  in attempt 3 of 3. The exception is: ReadTimeout: HTTPSConnectionPool(host='[da.gd](http://da.gd/)', port=443): Read timed out. (read timeout=3)

No further errors were observed later.

**Comment by phuzion** [comment]
Please provide timestamps.

**Comment by relrod** [comment]
We monitor things just fine and from multiple locations. This was not an issue on our end. Good day.

**Comment by phuzion** [comment]
As @relrod mentioned, we do have extensive monitoring and logging. However, our service receives hundreds of thousands of requests per day, so we are simply requesting more information in order to narrow down the timeframe. It's the holiday season, neither I nor the rest of the **entirely volunteer team** that runs this site has the time to go on a wild goose chase to search for what is more than likely an upstream network hiccup that we have no control over. If you want a URL shortener with an SLA, there are plenty of them out there that provide support with paid plans. Our service is best effort; if that is unacceptable to you, then I suggest you find an alternative that meets your needs.
