### ISSUE TITLE
Site performance is extremely degraded

### ISSUE THREAD

**Issue by impredicative** [relrod/dagd#68]
Site is not working normally. Almost all requests continue to fail.

![Screenshot from 2023-12-18 10-54-58](https://github.com/dagd/dagd/assets/566650/08876f97-f70f-4fda-a870-fd51a5df1ddb)

This issue has been opened because the previous issue #67 was wrongly closed.

**Comment by phuzion** [comment]
> This issue has been opened because the previous issue https://github.com/dagd/dagd/issues/67 was wrongly closed.

I will remind you once again that this service is provided entirely by volunteers and [as I have mentioned before](https://github.com/dagd/dagd/issues/58#issuecomment-1364437284), we do not provide an SLA for this service. I'd advise you to have an eggnog, chill out, and relax, it's just software.

In the meantime, I have figured out the root cause, resolved it, and the site is back to its normal operating status.

**Comment by relrod** [comment]
@impredicative Also, note that we actually _do_ have monitoring set up on the site. We do get alerts and notifications and pages if the site goes down (or has other issues that most users never see). We keep fairly extensive metrics and things like query times, index hitrates, a bunch of other stuff, trigger alerts.

You don't need to raise an issue every time there's a blip or outage, I assure you we know about it well before we ever see the github issue -- because when we are in a position to work on/fix the issue, we are focusing on that (based on the alerts and metrics), and not looking at github issues.
